version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/project
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v31-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v31-dependencies-

      - run: npm install
      - run: npm run bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v31-dependencies-{{ checksum "package-lock.json" }}

      - run: npm test
      - store_artifacts:
          # /home/circleci/project/packages/angular-freezeframe/projects/angular-freezeframe/node_modules/
          path: /home/circleci/.npm/_logs/
